//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IceCream {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class XBOXIceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XBOXIceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IceCream.XBOXIceResources", typeof(XBOXIceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Arial {
            get {
                object obj = ResourceManager.GetObject("Arial", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BloomCombineEffect {
            get {
                object obj = ResourceManager.GetObject("BloomCombineEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] BloomExtractEffect {
            get {
                object obj = ResourceManager.GetObject("BloomExtractEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DefaultParticleTexture {
            get {
                object obj = ResourceManager.GetObject("DefaultParticleTexture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] DefaultTileGridTexture {
            get {
                object obj = ResourceManager.GetObject("DefaultTileGridTexture", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] diagnosticFont {
            get {
                object obj = ResourceManager.GetObject("diagnosticFont", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GaussianBlurEffect {
            get {
                object obj = ResourceManager.GetObject("GaussianBlurEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] RefractionLayerEffect {
            get {
                object obj = ResourceManager.GetObject("RefractionLayerEffect", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
